[build]
buildCommand = "pip install -r webapp/backend/requirements.txt"
watchPatterns = ["/webapp/backend/**", "/webapp/backend/railway.toml"]

[deploy]
startCommand = "uvicorn webapp.backend.main:app --host 0.0.0.0 --port $PORT"
